# Generated by Django 5.0.6 on 2024-06-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_added_alter_article_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
